### ISSUE TITLE
Parcel

### ISSUE THREAD

**Issue by Skyline404** [csstools/postcss-font-magician#103]
**Parcel: 2.0.0-rc.0**

.postcssrc 
```
{
    "plugins":  {
        "postcss-font-magician": {}
    }
}
```
app.css
```
body  {
   font-family: "Alice";
}
```

But nothing is generated in bundle.css

**Comment by MrAwesomeRocks** [comment]
Can confirm, no `@font-face` rules are generated.

**Comment by romainmenke** [comment]
Please provide a minimap repo.
Going to close for now, but happy to revisit if new info is provided.
