### ISSUE TITLE
Hosted Fonts Not Appearing

### ISSUE THREAD

**Issue by realchriswells** [csstools/postcss-font-magician#25]
I'm having some issues with the hosted option for this module.

I've got this is my gulpfile.js

```
var post = [
    fonts({
        hosted: '../fonts/'
    }),
    autoprefixer,
    cssnano({
        discardComments: {
            removeAll: true
        }
    }),
    cssnext
];

gulp.task('styles', function () {
    gulp.src('./scss/{,*/}*.{scss,sass}')
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(postcss(post))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('dist/css'))
        .pipe(notify({message: 'CSS Processed', onLast: true}));
});
```

I'm calling this in my scss file:

```
body {
    font-family: "EffraMedium-Regular", serif;
    color: $text;
    font-size: 14px;
    @include susy-breakpoint($desktop) {
        font-size: 16px;
    }
}
```

But for some reason the font isn't being called.

The fonts are in the structure shown in the image attached.

<img width="274" alt="screen shot 2016-04-06 at 15 47 59" src="https://cloud.githubusercontent.com/assets/969168/14320951/0e48aa5c-fc0f-11e5-8fba-af7463881574.png">

Is there a specific way to reference the fonts?

**Comment by diessica** [comment]
The documentation isn't clear about hosted fonts. :/

**Comment by PierrickGT** [comment]
The hosted font option seems not to work at all.
I recommend you to use the custom option if you want to load hosted fonts.

**Comment by realchriswells** [comment]
@PierrickGT I tried using the custom option but it didn't seem to work either, although I'm not ruling out me not using it properly.

Do you have an example of this working?

**Comment by AgtLucas** [comment]
I've tried this: https://github.com/jonathantneal/postcss-font-magician/issues/1#issuecomment-144204760 but not joy. :/

**Comment by PierrickGT** [comment]
@realchriswells I'll make a Git repo when I'll have some free time.
That being said, it's pretty useless since it's longer than a @font-face declaration...

**Comment by brendan8c** [comment]
The problem is urgent! And this plugin absolutely does not work for gulp...
I delete it.

**Comment by PierrickGT** [comment]
> The problem is urgent! And this plugin absolutely does not work for gulp...
> I delete it.

5 years later and it's still urgent? 😅
