### ISSUE TITLE
Override old font faces

### ISSUE THREAD

**Issue by eduarddotgg** [csstools/postcss-font-magician#31]
It would be great if there was an option that could override old `@font-face`s for new ones.

It can be helpful for css refactoring, when for example project before required woff, ttf, eof and from some moment will require only woff and woff2.

What do you think?

**Comment by cmnstmntmn** [comment]
@iamfrntdv that belongs to the build script you have; you should change the options and you'll get a different output.

**Comment by iamfrntdv** [comment]
I mean if there is already declared ```@font-face``` in CSS it would be great if font-magician could override it. Especially useful for legacy css.

**Comment by romainmenke** [comment]
This will never be added.
It is an explicit feature of `font-magician` that it does not override existing `@font-face` rules.
