### ISSUE TITLE
Only reading woff file from a hosted (local) directory

### ISSUE THREAD

**Issue by peterdillon** [csstools/postcss-font-magician#4]
I am using grunt - I have all four font types (eot, svg, ttf and woff) - but the plugin only writes:

```
@font-face {
  font-family: notify;
  font-style: 400;
  font-weight: normal;
  src: local(notify),local(notify),url(path/.../fonts/notify.woff) format("woff");
}
```

Note: this is an icon-font. Not sure that makes a difference though.
Thank you in advance for this awesome plugin

**Comment by ddrevnov** [comment]
I have too on windows and gulp:
`@font-face {`
  `font-family: Roboto;`
  `font-style: 400;`
 ` font-weight: normal;`
  `src: local("Roboto Regular"),local(Roboto-Regular),url(../../c:/Users/Den/Dropbox/home/square/app/fonts/Roboto/Roboto-Regular.woff) format("woff"),url(../../c:/Users/Den/Dropbox/home/square/app/fonts/Roboto/Roboto-Regular.ttf) format("truetype");
}`

**Comment by jonathantneal** [comment]
It should parser all but EOT and SVG, so I’m sorry to hear about this. @andyjansson is working on entirely new parsers written from scratch for Font Magician (they happen to be built as excellent stand alone apps as well) that we’ll be incorporating into a new version that should be released in the next few weeks.

**Comment by romainmenke** [comment]
You can set the `formats` option to `formats: ['woff', 'ttf']`.
This will at least allow you to use `ttf` files.

Other issues should be reported upstream in : https://github.com/jonathantneal/directory-fonts-complete

Thank you for reaching out about this.
