### ISSUE TITLE
Material Icons @font-face rule not generated

### ISSUE THREAD

**Issue by tmb-github** [csstools/postcss-font-magician#48]
The very useful Material Icons font by Google, hosted at fonts.gstatic.com, would be a welcome addition to the font-face generation. There's no complete @font-face rule I can find online for the URLs for each of the fonts at fonts.gstatic.com.

**Comment by rajdee** [comment]
Hi @tmb-github The `Material Icons` was supported in [v2.3.0](https://github.com/jonathantneal/postcss-font-magician/releases/tag/v2.3.1)
It’s enough to use the font-family `Material Icons` in your css

**Comment by romainmenke** [comment]
Closing as this has shipped
