### ISSUE TITLE
Is there a way to make this work with Google Material Icons?

### ISSUE THREAD

**Issue by peterdillon** [csstools/postcss-font-magician#5]
http://google.github.io/material-design-icons/#icon-font-for-the-web

I notice the embed url for material icons is slightly different.

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by andyjansson** [comment]
This will be possible in the upcoming version of Font Magician.

**Comment by fingermaster** [comment]
Great to hear! Thank you for this amazing plugin.

**Comment by hellraiserrob** [comment]
Hi all, has there been any movement on this? Have had a search around and tried a few things, but couldn't get anything working.

**Comment by rajdee** [comment]
Hi @hellraiserrob @peterdillon 
The `Material Icons` was supported in [v2.3.0](https://github.com/jonathantneal/postcss-font-magician/releases/tag/v2.3.1)
It’s enough to use the font-family `Material Icons` in your css

**Comment by romainmenke** [comment]
Closing as this shipped
