### ISSUE TITLE
feature request: support wildcards in paths

### ISSUE THREAD

**Issue by bekanntmacher** [csstools/postcss-font-magician#59]
if you have got more than one font:

-- brown
--- brown-standard.woff
--- brown-bold.woff
-- font2
--- font2.woff`

`fontmagician({
                            hosted: ['../public/fonts/**/','/files/public/fonts/**/']
                        }),`

**Comment by romainmenke** [comment]
I don't think wildcards are the right way to go.
I am not going to add this here.

You can open an upstream issue here : https://github.com/jonathantneal/directory-fonts-complete
