### ISSUE TITLE
Error: url.replace is not a function, not handlinghosted fonts

### ISSUE THREAD

**Issue by mikemcguire** [csstools/postcss-font-magician#62]
I've spent a lot of time trying to get hosted fonts to work and dealing with a variety of issues

npm: 3.8.6
gulp-postcss: 7.0.1
postcss-font-magician: 2.1.1
node: 5.12.0

When I add a second argument to the hosted options I get the following error
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
TypeError: url.replace is not a function
    at removeTrailingSlash (/project/node_modules/postcss-font-magician/index.js:111:14)
```

I've also tried running without the second parameter and it simply won't load my hosted fonts whatsoever. The documentation isn't clear, it says it's relative to the project root, but not how the project root is determined. Is this based upon where my gulp file is located? Where the file that is running my postcss tasks located? Where my package.json is located? 

I've tried specifying my hosted directory from all of those locations with no results.

**Comment by rajdee** [comment]
Hi @mikemcguire  Please provide more information your settings for `postcss-font-magician` and file structure with of your project and fonts

**Comment by elpic** [comment]
Hi @mikemcguire, I did have the same issue and the problem was with the second argument it should be a string instead of an array. Please let me know if that works for you.

**Comment by mikemcguire** [comment]
@elpic Ah! That makes sense now. @rajdee I completely agree with elpic I also thought it was supposed to be an array. I honestly think the documentation should not have the square brackets, I understood the 2nd argument was optional via reading the description. 

I'll give it a try and see if that resolves my issue. Otherwise I'll post my project structure .
