### ISSUE TITLE
Question: How do you specify comma-delimited `font-family`?

### ISSUE THREAD

**Issue by zjijz** [csstools/postcss-font-magician#66]
It seems that the plugin doesn't parse comma-delimited `font-family`s correctly and doesn't generate the necessary font families. I have everything working if I only specify `font-family` as one font name.

**Comment by goncharov** [comment]
Seems `font-magician` can loads only first font in `font-family` lists [index.js#L242](https://github.com/jonathantneal/postcss-font-magician/blob/master/index.js#L242)

**Comment by romainmenke** [comment]
That is correct, the assumption is that fallbacks are always local or web safe fonts.
