### ISSUE TITLE
Not working for me with hosted option

### ISSUE THREAD

**Issue by jitendravyas** [csstools/postcss-font-magician#8]
my gulp setting

```
   .pipe(
      postcss([
         require('postcss-font-magician')({ hosted: '../assets/fonts' }),
         require('postcss-responsive-type'),
         require('autoprefixer')({ browsers: ['last 2 versions'] }),

      ])
   )
```

input 

```
body {
   font-family: "centralesans-light-webfont";
}
```

output

```
body {
  font-family: "centralesans-light-webfont"; }
```

**Comment by jonathantneal** [comment]
And you have `centralesans-light-webfont.woff` in the `../assets/fonts` directory?

**Comment by jitendravyas** [comment]
Yes

![font-packs json ola-wptheme 2015-09-11 18-58-06](https://cloud.githubusercontent.com/assets/77309/9815903/19f3bfe6-58b7-11e5-9a87-ea4d407466ab.jpg)

**Comment by jitendravyas** [comment]
Did you check this?

**Comment by ngsteel** [comment]
Hi, jitendravyas. Do you resolve it ?

**Comment by jitendravyas** [comment]
don't remember now 😦

*Jitendra Vyas*

**Comment by romainmenke** [comment]
Closing as this has been open for too long :/
