### ISSUE TITLE
Support new Material Icons styles

### ISSUE THREAD

**Issue by irritant** [csstools/postcss-font-magician#85]
First, thanks for a very useful plugin. 

It looks like support for Material Icons is currently limited to the basic icon style. There are several new styles such as Outlined (https://material.io/resources/icons/?style=outline) that postcss-font-magician doesn't seem to know about. It would be nice to be able to manage these styles the same way we manage the base styles, instead of having to include the Google hosted `script` tag or write our own font-face rules.

**Comment by romainmenke** [comment]
Please report this upstream in : https://github.com/jonathantneal/google-fonts-complete
