### ISSUE TITLE
Can't detect Inter font

### ISSUE THREAD

**Issue by cybervaldez** [csstools/postcss-font-magician#86]
Anyone else encounted an issue where google fonts is not being detected? Something like the font Inter(https://fonts.google.com/specimen/Inter)

**Comment by celestehorgan** [comment]
I'm facing a similar issue with [Lekton](https://fonts.google.com/specimen/Lekton). The 700 weight is detected and imports fine, but the 400 and 400 italic weights don't.

**Comment by btargac** [comment]
Facing the same issue with Inter

using webpack 4

postcss.config.js contains

```javascript
require('postcss-font-magician')({
      display: 'swap',
      variants: {
        Inter: {
          '300': [],
          '400': [],
          '700': [],
        },
      },
      foundries: ['google'],
      protocol: 'https:',
    }),
```

**Comment by celestehorgan** [comment]
fwiw for the rest of you: I eventually ditched `postcss-font-magician` and went with ye olde `<link>` shortcode from google fonts in the `<head>`:

```
<link href="https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"> 
```

Not ideal, but I honestly wonder if a part of the problem for me was using TailwindCSS. I originally tried out `postcss-font-magician` to try and solve an issue I was seeing with font imports on a live site using tailwind.

**Comment by codebling** [comment]
I had this issue with Open Sans. Putting the name in single quotes fixed it for me. I tried Inter and Lekton. Lekton worked (with or without quotes), Inter did not (even with quotes).

**Comment by jhorcl** [comment]
Facing the same issue with IBM Plex Mono with and without quotes.

**Comment by jhorcl** [comment]
this Module is using `google-fonts-complete`.

I think that the list of available fonts is outdated.

**Comment by romainmenke** [comment]
Please report this upstream in : https://github.com/jonathantneal/google-fonts-complete
