### ISSUE TITLE
Support link href stylesheet for Google fonts

### ISSUE THREAD

**Issue by anuragphadke** [csstools/postcss-font-magician#89]
Google fonts can also be added as a stylesheet:
```
<link href="https://fonts.googleapis.com/css?family=Oswald:400|Roboto:400|Roboto:400&display=swap"
                rel="stylesheet" />
```

The above removes the dependency to add @font-face in the css and the approach looks lot cleaner than the multitude of lines.

Is it possible to extend font-magician to support stylesheet?

**Comment by romainmenke** [comment]
That would be counter to the intention of this plugin.
This plugin aims to remove that separate stylesheet.
So adding it back would be unexpected :D
