### ISSUE TITLE
It doesn't work for gulp!

### ISSUE THREAD

**Issue by brendan8c** [csstools/postcss-font-magician#99]
There is not enough description. I am using gulp.
I have two folders:
**app/** -raw files
**build/** -ready files

```JavaScript
const postcssFontMagician = require('postcss-font-magician')
function fontMagic() {
    return src('build/style')
        .pipe(postcss([postcssFontMagician]))
        .pipe(dest('build/style'))
}
exports.stream = series(fontMagic)
```

How does he find the fonts folder?
I don't see where to specify the fonts folder...

I convert fonts to woff and woff2 > transfer them to the **build/fonts** folder > My scss files are converted to a css minified file > transfer it to the **build/style** folder > run the **fontMagic()** function and nothing happens...
In the styles, I indicated the name of the font...
```css
body {
    font-family: 'Museo Cyrl 500';
    font-size: 18px;
    line-height: 27px;
    font-weight: 300;
    color: #838383;
}
```
css style file cannot be specified in the same folder? Or is it possible?
As I understand it: the plugin enters the stylesheet, finds the declared font, and somehow finds it in the nearby folder with fonts ..? And then overwrites that style file by adding properties for the font?

You need to explain how this plugin works ... Where you need to specify the path to the folder with fonts.
Does it work with scss files? Yes or no?
Will it overwrite the same style file if you point to an already compiled css file? Yes or no?

Why does this record not work then..?
```JavaScript
const postcssFontMagician = require('postcss-font-magician')
function scss() {
    let plugins = [
        postcssFontMagician(),
        autoprefixer(),
        cssnano()
    ];

    return src(config.app.style)
        .pipe(sass())
        .pipe(concat('style.min.css'))
        .pipe(postcss(plugins))
        .pipe(dest(config.build.style)
}
exports.stream = series(scss)
```
I understand correctly? The plugin itself has to connect the fonts? After all, this is its essence...
I'm waiting for your help... I've tried a lot already but nothing worked.

**Comment by brendan8c** [comment]
The problem is urgent! And this plugin absolutely does not work for gulpю...
I delete it.

**Comment by romainmenke** [comment]
Please provide a minimal reproduction.
A GitHub repo I can pull and run.

Going to close for now, but happy to revisit if new info is provided.
